-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";
-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';
-- Create "items" table
CREATE TABLE "public"."items" (
  "item" text NOT NULL,
  CONSTRAINT "Items_pkey" PRIMARY KEY ("item")
);
-- Create "alerts" table
CREATE TABLE "public"."alerts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "item" text NOT NULL,
  "alert_type" integer NULL,
  "price_trigger" integer NULL,
  CONSTRAINT "Alerts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Alerts_Item_fkey" FOREIGN KEY ("item") REFERENCES "public"."items" ("item") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "trades" table
CREATE TABLE "public"."trades" (
  "item" text NOT NULL,
  "time_stamp" timetz NOT NULL,
  "price" integer NOT NULL,
  CONSTRAINT "Trades_pkey" PRIMARY KEY ("time_stamp"),
  CONSTRAINT "Items_Item_fkey" FOREIGN KEY ("item") REFERENCES "public"."items" ("item") ON UPDATE NO ACTION ON DELETE NO ACTION
);
